title: MicroStack

author:
  name: GitHub User
  email: your-email@domain.com
  
description: > # this means to ignore newlines until "show_excerpts:"
  Wireless network security
  
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

social_links:
    twitter: MicroStackIoT
    github:  kpyush
    facebook: ustack
    instagram: microstackiot
    linkedin: company/microstackiot
    
header_pages:
  - about.md
